"""initial tables: recordings, tasks

Revision ID: c1100b151fca
Revises: 
Create Date: 2026-09-11 14:37:27.279682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1100b151fca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_ext', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('transcript', sa.Text().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('last_status', sa.Enum('pending', 'transcribing', 'summarizing', 'done', 'failed', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uk_recordings_file_hash'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    )
    op.create_index('idx_recordings_created_at', 'recordings', ['created_at'], unique=False)
    op.create_index('idx_recordings_last_status', 'recordings', ['last_status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'transcribing', 'summarizing', 'done', 'failed', name='taskstatus'), nullable=False),
    sa.Column('current_stage_retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('total_retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name='fk_tasks_recording_id__recordings_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    )
    op.create_index('idx_tasks_recording_id', 'tasks', ['recording_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 直接 DROP TABLE 自动移除其上所有索引/外键/约束，
    # 避免 MySQL 1553 "Cannot drop index needed in a foreign key constraint"。
    op.drop_table('tasks')
    op.drop_index('idx_recordings_last_status', table_name='recordings')
    op.drop_index('idx_recordings_created_at', table_name='recordings')
    op.drop_table('recordings')
    # ### end Alembic commands ###
